#!/usr/bin/env bash


pip install . --break-system-packages
cp config/wp-reaction.conf /etc/systemd/
cp config/wp-reaction.service /etc/systemd/system/

systemctl enable wp-reaction
systemctl start wp-reaction
