#!/usr/bin/env bash


pip install . --break-system-packages
if [ ! -f /etc/systemd/wp-reaction.conf ]; then cp config/wp-reaction.conf /etc/systemd/; fi
cp config/wp-reaction.service /etc/systemd/system/

systemctl enable wp-reaction
systemctl start wp-reaction
